<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="2" ignored="0" total="3" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="47625" started-at="2017-09-18T15:52:20Z" finished-at="2017-09-18T15:53:08Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="47625" started-at="2017-09-18T15:52:20Z" finished-at="2017-09-18T15:53:08Z">
      <class name="SCB.SCM_Automation.TestCase5">
        <test-method status="PASS" signature="initialize()[pri:0, instance:SCB.SCM_Automation.TestCase5@8e7350]" name="initialize" is-config="true" duration-ms="242" started-at="2017-09-18T21:22:20Z" finished-at="2017-09-18T21:22:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method status="PASS" signature="precondition(java.lang.reflect.Method)[pri:0, instance:SCB.SCM_Automation.TestCase5@8e7350]" name="precondition" is-config="true" duration-ms="14501" started-at="2017-09-18T21:22:20Z" finished-at="2017-09-18T21:22:35Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void SCB.SCM_Automation.TestCase5.Test_case_1() throws com.codoid.products.exception.FilloException,java.io.IOException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- precondition -->
        <test-method status="FAIL" signature="Test_case_1()[pri:0, instance:SCB.SCM_Automation.TestCase5@8e7350]" name="Test_case_1" duration-ms="6875" started-at="2017-09-18T21:22:35Z" finished-at="2017-09-18T21:22:42Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Thank you for your registration] but found [Error: Username already exists]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Thank you for your registration] but found [Error: Username already exists]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at SCB.SCM_Automation.TestCase5.Test_case_1(TestCase5.java:87)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test_case_1 -->
        <test-method status="PASS" signature="Reporter(org.testng.ITestResult)[pri:0, instance:SCB.SCM_Automation.TestCase5@8e7350]" name="Reporter" is-config="true" duration-ms="776" started-at="2017-09-18T21:22:42Z" finished-at="2017-09-18T21:22:43Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Test_case_1 status=FAILURE method=TestCase5.Test_case_1()[pri:0, instance:SCB.SCM_Automation.TestCase5@8e7350] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Reporter -->
        <test-method status="PASS" signature="precondition(java.lang.reflect.Method)[pri:0, instance:SCB.SCM_Automation.TestCase5@8e7350]" name="precondition" is-config="true" duration-ms="12329" started-at="2017-09-18T21:22:43Z" finished-at="2017-09-18T21:22:55Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void SCB.SCM_Automation.TestCase5.testCase_2()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- precondition -->
        <test-method status="SKIP" signature="testCase_2()[pri:0, instance:SCB.SCM_Automation.TestCase5@8e7350]" name="testCase_2" duration-ms="2" started-at="2017-09-18T21:22:55Z" finished-at="2017-09-18T21:22:55Z">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[This test case is skipped]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: This test case is skipped
	at SCB.SCM_Automation.TestCase5.testCase_2(TestCase5.java:95)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCase_2 -->
        <test-method status="PASS" signature="Reporter(org.testng.ITestResult)[pri:0, instance:SCB.SCM_Automation.TestCase5@8e7350]" name="Reporter" is-config="true" duration-ms="21" started-at="2017-09-18T21:22:55Z" finished-at="2017-09-18T21:22:55Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testCase_2 status=SKIP method=TestCase5.testCase_2()[pri:0, instance:SCB.SCM_Automation.TestCase5@8e7350] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Reporter -->
        <test-method status="PASS" signature="precondition(java.lang.reflect.Method)[pri:0, instance:SCB.SCM_Automation.TestCase5@8e7350]" name="precondition" is-config="true" duration-ms="11612" started-at="2017-09-18T21:22:55Z" finished-at="2017-09-18T21:23:07Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void SCB.SCM_Automation.TestCase5.testCase_3()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- precondition -->
        <test-method status="FAIL" signature="testCase_3()[pri:0, instance:SCB.SCM_Automation.TestCase5@8e7350]" name="testCase_3" duration-ms="1" started-at="2017-09-18T21:23:07Z" finished-at="2017-09-18T21:23:07Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at org.testng.Assert.assertTrue(Assert.java:51)
	at SCB.SCM_Automation.TestCase5.testCase_3(TestCase5.java:102)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCase_3 -->
        <test-method status="PASS" signature="Reporter(org.testng.ITestResult)[pri:0, instance:SCB.SCM_Automation.TestCase5@8e7350]" name="Reporter" is-config="true" duration-ms="345" started-at="2017-09-18T21:23:07Z" finished-at="2017-09-18T21:23:07Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testCase_3 status=FAILURE method=TestCase5.testCase_3()[pri:0, instance:SCB.SCM_Automation.TestCase5@8e7350] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Reporter -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:SCB.SCM_Automation.TestCase5@8e7350]" name="tearDown" is-config="true" duration-ms="890" started-at="2017-09-18T21:23:07Z" finished-at="2017-09-18T21:23:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- SCB.SCM_Automation.TestCase5 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
